language: python

python:
  - "3.12"

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE=duesanddos.settings
    - PGHOST=127.0.0.1
    - PGPORT=5432
    - PGUSER=postgres
    - PGPASSWORD=
    - PGDATABASE=travis_ci_test

install:
  - pip install -r duesanddos/requirements.txt
  - pip install coverage 'coveralls[yaml]' flake8 black

before_script:
  - psql -h 127.0.0.1 -U postgres -d postgres -c 'CREATE DATABASE travis_ci_test;'
  - cd duesanddos

script:
  - black --check .
  - flake8 .
  - coverage run --source=accounts manage.py test

after_success:
  - coveralls --verbose