# Generated by Django 4.2.28 on 2026-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="fridge_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
