# Generated by Django 4.2.28 on 2026-04-12 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_options_settlement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date_spent",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
