# Generated by Django 4.2.28 on 2026-04-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_alter_expense_date_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="expensesplit",
            name="amount_owed",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="settlement",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
