# Generated by Django 4.2.28 on 2026-05-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "expenses",
            "0004_alter_expense_amount_alter_expensesplit_amount_owed_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="settlement",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Confirmation"),
                    ("CONFIRMED", "Confirmed"),
                    ("REJECTED", "Rejected"),
                    ("VOIDED", "Voided (No Debt)"),
                    ("DELETE_PENDING", "Deletion Requested"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
