# Generated by Django 4.2.28 on 2026-05-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_settlement_is_read"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="settlement",
            name="is_read",
        ),
    ]
