# Generated by Django 4.2.28 on 2026-05-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_remove_settlement_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
