# Generated by Django 4.2.28 on 2026-03-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="google_avatar_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
