# Generated by Django 4.2.28 on 2026-03-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_household_remove_profile_google_avatar_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="household",
            name="invite_code",
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
