# Generated by Django 4.2.28 on 2026-03-14 03:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_household_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.UploadToPath("profile_pics"),
            ),
        ),
    ]
