# Generated by Django 4.2.28 on 2026-03-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_avatar_unique_upload_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="default_rules",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="household",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
