# Generated by Django 4.2.28 on 2026-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_expense_split_type_expensesplit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="split_type",
            field=models.CharField(
                choices=[
                    ("EQUAL", "Split Equally"),
                    ("PERCENT", "Split by Percentage"),
                    ("AMOUNT", "Split by Amount ($)"),
                ],
                default="EQUAL",
                max_length=10,
            ),
        ),
    ]
