# Generated by Django 4.2.28 on 2026-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_remove_expensesplit_amount_owed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensesplit",
            name="amount_owed",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
