# Generated by Django 4.2.28 on 2026-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_expensesplit_amount_owed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensesplit",
            name="is_settled",
        ),
        migrations.RemoveField(
            model_name="expensesplit",
            name="settled_at",
        ),
        migrations.RemoveField(
            model_name="expensesplit",
            name="settled_by",
        ),
        migrations.AlterField(
            model_name="expensesplit",
            name="amount_owed",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
