# Generated by Django 4.2.28 on 2026-04-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_split_models_to_new_apps"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="default_calendar_view",
            field=models.CharField(
                choices=[
                    ("dayGridMonth", "Monthly"),
                    ("timeGridWeek", "Weekly"),
                    ("timeGridDay", "Daily"),
                ],
                default="dayGridMonth",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
    ]
