# Generated by Django 4.2.28 on 2026-04-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_profile_default_calendar_view_profile_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="personal_todo",
            field=models.TextField(blank=True, default=""),
        ),
    ]
