# Generated by Django 4.2.28 on 2026-04-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_profile_personal_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_deactivated",
            field=models.BooleanField(default=False),
        ),
    ]
