# Generated by Django 4.2.28 on 2026-04-10 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_alter_expense_options_settlement"),
        ("chores", "0005_remove_chore_google_event_id_choregoogleevent"),
        ("chat", "0002_backfill_household_group_conversations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.CreateModel(
            name="MessageReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        choices=[("EXPENSE", "Expense"), ("CHORE", "Chore")],
                        max_length=16,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "chore",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_references",
                        to="chores.chore",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_references",
                        to="expenses.expense",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="messagereference",
            constraint=models.UniqueConstraint(
                fields=("message", "position"),
                name="chat_unique_reference_position_per_message",
            ),
        ),
    ]
