# Generated by Django 4.2.28 on 2026-04-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_message_deletion_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hiddenmessage",
            new_name="chat_hidden_user_id_6eceed_idx",
            old_name="chat_hiddem_user_id_7c4521_idx",
        ),
    ]
