# Generated by Django 4.2.28 on 2026-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("EXPENSE_ADDED", "Expense Added"),
                    ("PAYMENT_SETTLED", "Payment Settled"),
                    ("HOUSEHOLD_JOINED", "Joined Household"),
                    ("MEMBER_REMOVED", "Member Removed"),
                    ("EXPENSE_DELETED", "Expense Deleted"),
                    ("EXPENSE_EDITED", "Expense Edited"),
                    ("CHORE_CREATED", "Chore Created"),
                    ("CHORE_UPDATED", "Chore Updated"),
                    ("CHORE_DELETED", "Chore Deleted"),
                    ("CHORE_COMPLETED", "Chore Completed"),
                ],
                max_length=20,
            ),
        ),
    ]
