# Generated by Django 4.2.28 on 2026-04-03 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("households", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "One-time"),
                            ("DAILY", "Recurring - Daily"),
                            ("WEEKLY", "Recurring - Weekly"),
                        ],
                        default="ONE_TIME",
                        max_length=10,
                    ),
                ),
                ("has_due_date", models.BooleanField(default=False)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("due_time", models.TimeField(blank=True, null=True)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("repeat_monday", models.BooleanField(default=False)),
                ("repeat_tuesday", models.BooleanField(default=False)),
                ("repeat_wednesday", models.BooleanField(default=False)),
                ("repeat_thursday", models.BooleanField(default=False)),
                ("repeat_friday", models.BooleanField(default=False)),
                ("repeat_saturday", models.BooleanField(default=False)),
                ("repeat_sunday", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_chores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_chores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chores",
                        to="households.household",
                    ),
                ),
            ],
            options={
                "ordering": ["description"],
            },
        ),
    ]
