# Generated by Django 4.2.28 on 2026-04-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0003_choreskip"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
