# Generated by Django 4.2.28 on 2026-04-06 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chores", "0004_chore_google_event_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chore",
            name="google_event_id",
        ),
        migrations.CreateModel(
            name="ChoreGoogleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_event_id", models.CharField(max_length=255)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_events",
                        to="chores.chore",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chore_syncs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("chore", "user")},
            },
        ),
    ]
